// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD9S8wz1Vkn2zzZiwidGyppslYEAdSIRU',
    appId: '1:39418500826:web:8a47e9cc05ff95c51577e3',
    messagingSenderId: '39418500826',
    projectId: 'fir-62c8d',
    authDomain: 'fir-62c8d.firebaseapp.com',
    storageBucket: 'fir-62c8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAorurfbneoEEU7_pnSYw6L3-mkfdebOZI',
    appId: '1:39418500826:android:0e6d7ee839c9ae661577e3',
    messagingSenderId: '39418500826',
    projectId: 'fir-62c8d',
    storageBucket: 'fir-62c8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALwG2DqRWaRR4GHtNkj-xBCvGvYxyrFYg',
    appId: '1:39418500826:ios:9e8aa717b5921a081577e3',
    messagingSenderId: '39418500826',
    projectId: 'fir-62c8d',
    storageBucket: 'fir-62c8d.appspot.com',
    iosBundleId: 'com.example.tradingApp',
  );
}
